### ISSUE TITLE
unable to locate qemu0 - net bridge qemu0: bridge helper failed

### ISSUE THREAD

**Issue by puccaso** [balena-labs-research/balena-virt#2]
Hello, 

trying to run this on a raspberry pi 4, the container builds fine, I eventually got the data on the device, but looks like qemu0 can't be found.

i played around a bit hoping that if qemu0 was missing, maybe br0 may be there, but that wasn't there either. virbr0 maybe? 
next:  testing bridged networking via a docker-compose setting... 

any help would be great. 

```
[Logs]    [9/8/2022, 00:29:44] [main] qemu-system-aarch64: -net bridge,br=qemu0: bridge helper failed
[Logs]    [9/8/2022, 00:29:44] [main] QEMU instance with PID 17 exited with code: 1, signal: null
[Logs]    [9/8/2022, 00:29:47] Restarting service 'main sha256:4facc191c9c591c2de12e3927be39b59a060c35a7dc674d82d3c37ec62330e5d'
[Logs]    [9/8/2022, 00:29:47] [main] Spawning 1 aarch64 children using template 'standard'
[Logs]    [9/8/2022, 00:29:47] [main] All instances are running
```

```


[Logs]    [9/8/2022, 00:44:21] Service exited 'main sha256:4facc191c9c591c2de12e3927be39b59a060c35a7dc674d82d3c37ec62330e5d'
[Logs]    [9/8/2022, 00:44:21] [main] failed to get mtu of bridge `br0': No such device
[Logs]    [9/8/2022, 00:44:21] [main] qemu-system-aarch64: -net bridge: bridge helper failed
[Logs]    [9/8/2022, 00:44:21] [main] QEMU instance with PID 17 exited with code: 1, signal: null

```

**Comment by jakogut** [comment]
Hello,

`qemu0` is a bridge that must be created on the host OS by the user, it doesn't exist by default in balenaOS. Refer to the documentation here: https://github.com/balena-io-playground/balenaVirt#shared-physical-device
